import { ThemeProvider } from "@/theme/ThemeProvider";
import clsx from "clsx";
import { GeistSans } from 'geist/font/sans';
import type { Metadata } from "next";
import "./globals.css";

const geistSans = GeistSans;


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={clsx(`${geistSans.className} antialiased`, "bg-background")}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
